(run 1 (out)
     (runo 'all
	   '(let ((==meta
		   (muo (e s/c r st k)
			(fresh (exp0 exp1 tm0 tm1 sub^ sub^^)
			       (==mk (exp0 exp1) e)
			       (rei-lookupo exp0 r st tm0)
			       ((muo (e1 s/c1 r1 st1 k1)
				     (fresh (sub0 c0 sub1 c1)
					    (rei-lookupo 's/c r1 st1 (sub0 c0))
					    (==mk (sub1 c1) s/c1)
					    (appendo sub0 sub1 sub^)
					    ;; add info about sub^ to sub1
					    (rei-lookupo 'sub^ r1 st1 sub^-var)
					    (rei-unifyo sub^-var sub^ sub1 sub1^)
					    (apply-cont-psh k1 sub1^ st1)
					    )
				     ))
			       ((muo (e1 s/c1 r1 st1 k1)
				     (fresh (sub0 c0 sub1 c1)
					    (==mk (sub1 c1) s/c1)
					    (rei-lookupo 'e r1 st1 tms-exp)
					    (==mk (tm0-exp tm1-exp) tms-exp)
					    (rei-lookupo tm1-exp r1 st1 tm1)
					    ;; add info about tm1 to sub1
					    (rei-lookupo 'tm1 r1 st1 tm1-var)
					    (rei-unifyo tm1-var tm1 sub1 sub1^)
					    (apply-cont-psh k1 sub1^ st1)
					    )
				     ))
			       
			       (rei-unifyo tm0 tm1 sub^ sub^^)
			       (apply-cont-psh k sub^^ st))))
		  (set-meta-a-and-eval (muo (e s/c r st k)
					    (fresh (meta-a e0 e1 e2)
						   (==mk e (e0 e1 e2))
						   (==mk meta-a ((42 43) (42 43)))
						   (meaning-mk (e1 e0 e2) s/c r st k)))))
	      (fresh (a b)
		     ;; first go to meta level to set up a var
		     (set-meta-a-and-eval (a a) ==mk b)
		     (==meta b meta-a)))
	   out))

